import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import checkout from '../api/checkout.js';import status from '../api/status/[pedido_id].js';import webhook from '../api/webhook.js';import config from '../api/config.js';
import {readToken,signToken} from '../lib/security.js';
const customer={name:'Maria Silva',email:'maria@example.com',phone:'45999999999',document:'52998224725',address:{street:'Rua Teste',number:'123',neighborhood:'Centro',city:'Cascavel',state:'PR',zipcode:'85810000'}};
const response=()=>({code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.data=v;return this;}});
const env={SHOP_READY:'true',APP_URL:'https://shop.example.com',SELLER_DETAILS:'TEST ONLY',ORDER_SECRET:'a'.repeat(64),MANGOFY_API_KEY:'TEST_KEY',MANGOFY_STORE_CODE:'TEST_STORE'};
function enable(){Object.assign(process.env,env);delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;}
function disable(){for(const k of Object.keys(env))delete process.env[k];}
function request(body={}){return {method:'POST',headers:{origin:env.APP_URL,'idempotency-key':randomUUID()},body:{items:[{id:'google-azul',variant:'Azul',quantity:25}],shipping_method:'standard',customer,payment_method:'pix',...body}};}
async function prepare(req){const r=response();await checkout({...req,body:{...req.body,action:'prepare'}},r);assert.equal(r.code,200);return {...req,body:{...req.body,action:'create',checkout_token:r.data.checkout_token}};}
test('unconfigured store refuses creation',async()=>{delete process.env.SHOP_READY;const r=response();await checkout({method:'POST',headers:{}},r);assert.equal(r.code,503);});
test('ready config needs no database variables',()=>{enable();try{const r=response();config({method:'GET'},r);assert.equal(r.data.ready,true);assert.equal(r.data.order_storage,'provider');assert.equal(r.data.payment_method,'pix');}finally{disable();}});
test('invalid origin, card, minimum and altered ticket never reach provider',async()=>{enable();const original=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw Error('should not call');};try{for(const req of [request({payment_method:'credit_card'}),request({items:[{id:'google-azul',variant:'Azul',quantity:4}]}),{...request(),headers:{origin:'https://evil.example.com','idempotency-key':randomUUID()}}]){const r=response();await checkout(req,r);assert.ok([400,403].includes(r.code));}const good=await prepare(request());const altered=response();await checkout({...good,body:{...good.body,shipping_method:'full'}},altered);assert.equal(altered.code,409);assert.equal(calls,0);}finally{global.fetch=original;disable();}});
test('prepare and create refuse over-limit totals and never trust a client amount',async()=>{enable();const original=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw Error('should not call');};try{for(const action of ['prepare','create'])for(const [quantity,shipping_method] of [[121,'standard'],[118,'full']]){const req=request({action,items:[{id:'google-azul',variant:'Azul',quantity}],shipping_method,total_cents:1,checkout_token:'forged'});const r=response();await checkout(req,r);assert.equal(r.code,400);assert.match(r.data.error,/limite por pagamento/);}const allowed=request({items:[{id:'google-azul',variant:'Azul',quantity:100}]});const ready=await prepare(allowed);assert.equal(readToken(ready.body.checkout_token,'prepare').total_cents,74900);const altered=response();await checkout({...ready,body:{...ready.body,items:[{id:'google-azul',variant:'Azul',quantity:121}],total_cents:74900}},altered);assert.equal(altered.code,400);assert.equal(calls,0);}finally{global.fetch=original;disable();}});
test('stateless receipt confirms directly from Mangofy, callbacks ignore posted approvals',async()=>{enable();const original=global.fetch;let creates=0,payment,postback;global.fetch=async(url,options)=>{assert.ok(String(url).startsWith('https://checkout.mangofy.com.br/'));if(options.method==='POST'){creates++;const body=JSON.parse(options.body);postback=body.postback_url;assert.equal(body.payment_amount,26665);assert.equal(body.shipping_amount,1690);payment={external_code:body.external_code,payment_code:'pay_test_1',payment_method:'pix',payment_amount:26665,shipping_amount:1690,payment_status:'pending',pix:{pix_qrcode_text:'TEST_ONLY_NOT_PAYABLE',pix_qrcode_image:'data:image/png;base64,AA==',pix_expires_at:'2099-01-01'}};}return Response.json(payment);};try{const req=await prepare(request({shipping_method:'full',total_cents:1}));const a=response();await checkout(req,a);assert.equal(a.code,201);assert.equal(a.data.status,'pending');const b=response();await checkout(req,b);assert.equal(creates,1);assert.equal(a.data.order_id,b.data.order_id);const receipt=readToken(a.data.access_token,'receipt');assert.equal(receipt.customer,undefined);assert.equal(receipt.total_cents,26665);const noAuth=response();await status({method:'GET',headers:{},query:{pedido_id:a.data.order_id}},noAuth);assert.equal(noAuth.code,403);const forged=response();await status({method:'GET',headers:{authorization:`Bearer ${a.data.access_token.slice(0,-1)}x`},query:{pedido_id:a.data.order_id}},forged);assert.equal(forged.code,403);const url=new URL(postback),w=response();await webhook({method:'POST',headers:{},query:Object.fromEntries(url.searchParams),body:{...payment,payment_status:'approved'}},w);assert.equal(w.code,200);const pending=response();await status({method:'GET',headers:{authorization:`Bearer ${a.data.access_token}`},query:{pedido_id:a.data.order_id}},pending);assert.equal(pending.data.status,'pending');payment.payment_status='approved';const s=response();await status({method:'GET',headers:{authorization:`Bearer ${a.data.access_token}`},query:{pedido_id:a.data.order_id}},s);assert.equal(s.data.status,'approved');assert.equal(s.data.customer,undefined);payment.payment_amount=1;const mismatch=response();await webhook({method:'POST',headers:{},query:Object.fromEntries(url.searchParams),body:payment},mismatch);assert.equal(mismatch.code,502);}finally{global.fetch=original;disable();}});
test('provider timeout is uncertain, one warm instance does not create again',async()=>{enable();const original=global.fetch;let creates=0;global.fetch=async()=>{creates++;throw Error('timeout');};try{const req=await prepare(request());const a=response();await checkout(req,a);assert.equal(a.code,202);assert.equal(a.data.status,'verification_required');const b=response();await checkout(req,b);assert.equal(b.code,202);assert.equal(creates,1);const r=response();await status({method:'GET',headers:{authorization:`Bearer ${a.data.access_token}`},query:{pedido_id:a.data.order_id}},r);assert.equal(r.data.status,'verification_required');assert.equal(creates,1);}finally{global.fetch=original;disable();}});
test('signed sessions expire and signatures cannot change their purpose',()=>{enable();try{const t=signToken('receipt',{id:'test'},-1);assert.throws(()=>readToken(t,'receipt'),/expirada/);const valid=signToken('prepare',{id:'test'});assert.throws(()=>readToken(valid,'receipt'));}finally{disable();}});
