import {randomUUID,createHash} from 'node:crypto';
import {quote} from '../public/js/catalog.js';
import {HttpError,validateCustomer} from '../lib/validation.js';
import {readiness} from '../lib/config.js';
import {redis,getOrder,saveOrder,rateLimit} from '../lib/db.js';
import {assertOrigin,begin,bodyOf,fail,tokenFor,webhookToken,ipKey} from '../lib/security.js';
import {gateway,payloadFor,verifyPayment,publicPayment,paymentPath} from '../lib/mangofy.js';
export default async function handler(req,res){if(!begin(req,res,'POST'))return;let order;
 try{if(!readiness())throw new HttpError(503,'A loja ainda está configurando os pagamentos. Nenhuma cobrança foi criada.');assertOrigin(req);await rateLimit(ipKey(req));const body=bodyOf(req);let q;try{q=quote(body.items);}catch(e){throw new HttpError(400,e.message);}const customer=validateCustomer(body.customer);if(body.payment_method!=='pix')throw new HttpError(400,'A TapStar aceita somente pagamento por Pix.');const key=req.headers['idempotency-key'];if(typeof key!=='string'||! /^[a-f0-9-]{36}$/i.test(key))throw new HttpError(400,'Reabra o checkout e tente novamente.');const fingerprint=createHash('sha256').update(JSON.stringify({q,customer,method:body.payment_method})).digest('hex');const lockKey=`checkout:${key}`;const id=`OP-${randomUUID()}`;const locked=await redis(['SET',lockKey,JSON.stringify({id,fingerprint}),'NX','EX',86400]);if(!locked){const prior=JSON.parse(await redis(['GET',lockKey])||'null');if(!prior||prior.fingerprint!==fingerprint)throw new HttpError(409,'Este pedido já foi usado. Reabra o checkout para alterar os dados.');const existing=await getOrder(prior.id);if(!existing)throw new HttpError(409,'Pedido em processamento. Aguarde antes de tentar novamente.');return res.status(200).json({...publicPayment(existing,existing.public_payment),access_token:tokenFor(existing.id)});}
 order={id,customer,quote:q,method:body.payment_method,status:'creating',created_at:new Date().toISOString()};order.postback=`${new URL(process.env.APP_URL).origin}/api/webhook?order=${id}&token=${webhookToken(id)}`;await saveOrder(order);const ip=String(req.headers['x-vercel-forwarded-for']||req.headers['x-forwarded-for']||req.socket?.remoteAddress||'').split(',')[0].trim();const payment=await gateway(paymentPath(order.method),payloadFor(order,ip));verifyPayment(order,payment);order.payment_code=payment.payment_code;order.status=payment.payment_status;order.public_payment={payment_status:payment.payment_status,...(payment.pix?{pix:payment.pix}:{})};await saveOrder(order);return res.status(201).json({...publicPayment(order,payment),access_token:tokenFor(order.id)});
 }catch(e){if(order){order.status='verification_required';try{await saveOrder(order);}catch{}return res.status(202).json({...publicPayment(order),access_token:tokenFor(order.id),message:'O resultado precisa ser verificado. Não crie outro pagamento para este pedido.'});}return fail(res,e);}}
